version: '3.7'
x-build-image: &build-image
  build:
    context: .
    cache_from:
      - illiad-templates
      - quay.io/nyulibraries/illiad-templates
      - quay.io/nyulibraries/illiad-templates:$BRANCH_NO_SLASH
  image: illiad-templates
  environment:
    BRANCH_NO_SLASH:

services:
  compile:
    <<: *build-image
    command: ["ruby", "compile.rb"]
    environment:
      ILLIAD_ENV:

  dev-deploy: &dev-deploy
    <<: *build-image
    environment:
      FTP_CMD: "put ./index-dev.html -o index.html; put ./error.asp; mput ./dist/views/*.html; cd ./javascripts; put ./dist/javascripts/illiad.js; cd ../stylesheets; put ./dist/stylesheets/illiad.css; cd ../ZMU; mput ./ZMU/*.html; cd ./javascripts; put ./ZMU/javascripts/illiad.js; cd ../stylesheets; put ./ZMU/stylesheets/illiad.css; cd ../images; mput ./ZMU/images/*; exit"
      FTP_USERNAME:
      FTP_PASSWORD:
      FTP_HOST:
      FTP_PROXY:
    # env_file:
    #   - test.env

  dev-setup:
    <<: *dev-deploy
    environment:
      FTP_CMD: "mkdir -p ./javascripts; mkdir -p ./stylesheets; mkdir -p ./images; mkdir -p ./ZMU/images; mkdir -p ./ZMU/stylesheets; mkdir -p ./ZMU/javascripts; exit;"

  prod-deploy: &prod-deploy
    <<: *build-image
    environment:
      FTP_CMD: "put ./index-prod.html -o index.html; put ./error.asp; mput ./dist/views/*.html; cd ./javascripts; put ./dist/javascripts/illiad.js; cd ../stylesheets; put ./dist/stylesheets/illiad.css; cd ../ZMU; mput ./ZMU/*.html; cd ./javascripts; put ./ZMU/javascripts/illiad.js; cd ../stylesheets; put ./ZMU/stylesheets/illiad.css; cd ../images; mput ./ZMU/images/*; exit"
      FTP_USERNAME:
      FTP_PASSWORD:
      FTP_HOST:
      FTP_PROXY:

  prod-setup:
    <<: *prod-deploy
    environment:
      FTP_CMD: "mkdir -p ./javascripts; mkdir -p ./stylesheets; mkdir -p ./images; mkdir -p ./ZMU/images; mkdir -p ./ZMU/stylesheets; mkdir -p ./ZMU/javascripts; exit;"
